"""Edit task table for status and assignee columns

Revision ID: 6713783e6aaf
Revises: 73f3c62e3848
Create Date: 2025-09-16 23:39:56.814941

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "6713783e6aaf"
down_revision: Union[str, Sequence[str], None] = "73f3c62e3848"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""



    task_status_enum = postgresql.ENUM(
        'OPEN', 'IN_PROGRESS', 'BLOCKED', 'COMPLETED',
        name='taskstatusenum'
    )
    task_status_enum.create(op.get_bind())


    op.add_column(
        "tasks",
        sa.Column(
            "task_status",
            sa.Enum(
                "OPEN",
                "IN_PROGRESS",
                "BLOCKED",
                "COMPLETED",
                name="taskstatusenum",
            ),
            nullable=False,
            server_default='OPEN'
        ),
    )
    op.add_column(
        "tasks", sa.Column("assignee", sa.String(length=100), nullable=True)
    )
    op.drop_column("tasks", "technician")



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "technician",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("tasks", "assignee")
    op.drop_column("tasks", "task_status")

    # Drop the ENUM type after dropping the column
    task_status_enum = postgresql.ENUM(
        'OPEN', 'IN_PROGRESS', 'BLOCKED', 'COMPLETED',
        name='taskstatusenum'
    )
    task_status_enum.drop(op.get_bind())
    # ### end Alembic commands ###