"""add description to task table

Revision ID: 3ff2c8c63ba7
Revises: 6713783e6aaf
Create Date: 2025-09-17 21:09:07.572367

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3ff2c8c63ba7"
down_revision: Union[str, Sequence[str], None] = "6713783e6aaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("task_description", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "task_description")
    # ### end Alembic commands ###
