services:
  db:
    image: postgres
    ports:
      - "3000:5432"
    environment:
      POSTGRES_USER: default_teamlytics_user
      POSTGRES_PASSWORD: default_teamlytics_password
      POSTGRES_DB: teamlytics
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}

