/* tslint:disable */
/* eslint-disable */
/**
 * My FastAPI App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskStatusEnum } from './TaskStatusEnum';
import {
    TaskStatusEnumFromJSON,
    TaskStatusEnumFromJSONTyped,
    TaskStatusEnumToJSON,
    TaskStatusEnumToJSONTyped,
} from './TaskStatusEnum';

/**
 * 
 * @export
 * @interface CompletedTask
 */
export interface CompletedTask {
    /**
     * 
     * @type {number}
     * @memberof CompletedTask
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof CompletedTask
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CompletedTask
     */
    description: string;
    /**
     * 
     * @type {TaskStatusEnum}
     * @memberof CompletedTask
     */
    status: TaskStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof CompletedTask
     */
    assignee: string;
    /**
     * 
     * @type {string}
     * @memberof CompletedTask
     */
    estimated_time: string;
    /**
     * 
     * @type {Date}
     * @memberof CompletedTask
     */
    desired_completion_date: Date;
    /**
     * 
     * @type {string}
     * @memberof CompletedTask
     */
    notes?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CompletedTask
     */
    timestamp: Date;
}



/**
 * Check if a given object implements the CompletedTask interface.
 */
export function instanceOfCompletedTask(value: object): value is CompletedTask {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('assignee' in value) || value['assignee'] === undefined) return false;
    if (!('estimated_time' in value) || value['estimated_time'] === undefined) return false;
    if (!('desired_completion_date' in value) || value['desired_completion_date'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function CompletedTaskFromJSON(json: any): CompletedTask {
    return CompletedTaskFromJSONTyped(json, false);
}

export function CompletedTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompletedTask {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
        'status': TaskStatusEnumFromJSON(json['status']),
        'assignee': json['assignee'],
        'estimated_time': json['estimated_time'],
        'desired_completion_date': (new Date(json['desired_completion_date'])),
        'notes': json['notes'] == null ? undefined : json['notes'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function CompletedTaskToJSON(json: any): CompletedTask {
    return CompletedTaskToJSONTyped(json, false);
}

export function CompletedTaskToJSONTyped(value?: CompletedTask | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'status': TaskStatusEnumToJSON(value['status']),
        'assignee': value['assignee'],
        'estimated_time': value['estimated_time'],
        'desired_completion_date': ((value['desired_completion_date']).toISOString()),
        'notes': value['notes'],
        'timestamp': ((value['timestamp']).toISOString()),
    };
}

