/* tslint:disable */
/* eslint-disable */
/**
 * My FastAPI App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskId } from './TaskId';
import {
    TaskIdFromJSON,
    TaskIdFromJSONTyped,
    TaskIdToJSON,
    TaskIdToJSONTyped,
} from './TaskId';

/**
 * 
 * @export
 * @interface CompletedUser
 */
export interface CompletedUser {
    /**
     * 
     * @type {number}
     * @memberof CompletedUser
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof CompletedUser
     */
    role: string;
    /**
     * 
     * @type {string}
     * @memberof CompletedUser
     */
    first_name: string;
    /**
     * 
     * @type {string}
     * @memberof CompletedUser
     */
    last_name: string;
    /**
     * 
     * @type {string}
     * @memberof CompletedUser
     */
    context_field: string;
    /**
     * 
     * @type {TaskId}
     * @memberof CompletedUser
     */
    current_task: TaskId | null;
    /**
     * 
     * @type {Array<TaskId>}
     * @memberof CompletedUser
     */
    queued_task: Array<TaskId>;
    /**
     * 
     * @type {Date}
     * @memberof CompletedUser
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the CompletedUser interface.
 */
export function instanceOfCompletedUser(value: object): value is CompletedUser {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('first_name' in value) || value['first_name'] === undefined) return false;
    if (!('last_name' in value) || value['last_name'] === undefined) return false;
    if (!('context_field' in value) || value['context_field'] === undefined) return false;
    if (!('current_task' in value) || value['current_task'] === undefined) return false;
    if (!('queued_task' in value) || value['queued_task'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function CompletedUserFromJSON(json: any): CompletedUser {
    return CompletedUserFromJSONTyped(json, false);
}

export function CompletedUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompletedUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'role': json['role'],
        'first_name': json['first_name'],
        'last_name': json['last_name'],
        'context_field': json['context_field'],
        'current_task': TaskIdFromJSON(json['current_task']),
        'queued_task': ((json['queued_task'] as Array<any>).map(TaskIdFromJSON)),
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function CompletedUserToJSON(json: any): CompletedUser {
    return CompletedUserToJSONTyped(json, false);
}

export function CompletedUserToJSONTyped(value?: CompletedUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'role': value['role'],
        'first_name': value['first_name'],
        'last_name': value['last_name'],
        'context_field': value['context_field'],
        'current_task': TaskIdToJSON(value['current_task']),
        'queued_task': ((value['queued_task'] as Array<any>).map(TaskIdToJSON)),
        'timestamp': ((value['timestamp']).toISOString()),
    };
}

