/* tslint:disable */
/* eslint-disable */
/**
 * My FastAPI App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskStatusEnum } from './TaskStatusEnum';
import {
    TaskStatusEnumFromJSON,
    TaskStatusEnumFromJSONTyped,
    TaskStatusEnumToJSON,
    TaskStatusEnumToJSONTyped,
} from './TaskStatusEnum';

/**
 * 
 * @export
 * @interface Task
 */
export interface Task {
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    description: string;
    /**
     * 
     * @type {TaskStatusEnum}
     * @memberof Task
     */
    status: TaskStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof Task
     */
    estimated_time: number;
    /**
     * 
     * @type {Date}
     * @memberof Task
     */
    desired_completion_date: Date;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    notes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    assignee?: string | null;
}



/**
 * Check if a given object implements the Task interface.
 */
export function instanceOfTask(value: object): value is Task {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('estimated_time' in value) || value['estimated_time'] === undefined) return false;
    if (!('desired_completion_date' in value) || value['desired_completion_date'] === undefined) return false;
    return true;
}

export function TaskFromJSON(json: any): Task {
    return TaskFromJSONTyped(json, false);
}

export function TaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): Task {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'status': TaskStatusEnumFromJSON(json['status']),
        'estimated_time': json['estimated_time'],
        'desired_completion_date': (new Date(json['desired_completion_date'])),
        'notes': json['notes'] == null ? undefined : json['notes'],
        'assignee': json['assignee'] == null ? undefined : json['assignee'],
    };
}

export function TaskToJSON(json: any): Task {
    return TaskToJSONTyped(json, false);
}

export function TaskToJSONTyped(value?: Task | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'status': TaskStatusEnumToJSON(value['status']),
        'estimated_time': value['estimated_time'],
        'desired_completion_date': ((value['desired_completion_date']).toISOString()),
        'notes': value['notes'],
        'assignee': value['assignee'],
    };
}

