/* tslint:disable */
/* eslint-disable */
/**
 * My FastAPI App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HTTPStatus } from './HTTPStatus';
import {
    HTTPStatusFromJSON,
    HTTPStatusFromJSONTyped,
    HTTPStatusToJSON,
    HTTPStatusToJSONTyped,
} from './HTTPStatus';

/**
 * 
 * @export
 * @interface TaskFailure
 */
export interface TaskFailure {
    /**
     * 
     * @type {string}
     * @memberof TaskFailure
     */
    reason: string;
    /**
     * 
     * @type {HTTPStatus}
     * @memberof TaskFailure
     */
    status: HTTPStatus;
}



/**
 * Check if a given object implements the TaskFailure interface.
 */
export function instanceOfTaskFailure(value: object): value is TaskFailure {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function TaskFailureFromJSON(json: any): TaskFailure {
    return TaskFailureFromJSONTyped(json, false);
}

export function TaskFailureFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskFailure {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'],
        'status': HTTPStatusFromJSON(json['status']),
    };
}

export function TaskFailureToJSON(json: any): TaskFailure {
    return TaskFailureToJSONTyped(json, false);
}

export function TaskFailureToJSONTyped(value?: TaskFailure | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
        'status': HTTPStatusToJSON(value['status']),
    };
}

