/* tslint:disable */
/* eslint-disable */
/**
 * My FastAPI App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskId
 */
export interface TaskId {
    /**
     * 
     * @type {number}
     * @memberof TaskId
     */
    id: number;
}

/**
 * Check if a given object implements the TaskId interface.
 */
export function instanceOfTaskId(value: object): value is TaskId {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function TaskIdFromJSON(json: any): TaskId {
    return TaskIdFromJSONTyped(json, false);
}

export function TaskIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskId {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function TaskIdToJSON(json: any): TaskId {
    return TaskIdToJSONTyped(json, false);
}

export function TaskIdToJSONTyped(value?: TaskId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

