/* tslint:disable */
/* eslint-disable */
/**
 * My FastAPI App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum TaskStatusEnum {
    OPEN = 'OPEN',
    IN_PROGRESS = 'IN_PROGRESS',
    BLOCKED = 'BLOCKED',
    COMPLETED = 'COMPLETED'
}


export function instanceOfTaskStatusEnum(value: any): boolean {
    for (const key in TaskStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(TaskStatusEnum, key)) {
            if (TaskStatusEnum[key as keyof typeof TaskStatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TaskStatusEnumFromJSON(json: any): TaskStatusEnum {
    return TaskStatusEnumFromJSONTyped(json, false);
}

export function TaskStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskStatusEnum {
    return json as TaskStatusEnum;
}

export function TaskStatusEnumToJSON(value?: TaskStatusEnum | null): any {
    return value as any;
}

export function TaskStatusEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): TaskStatusEnum {
    return value as TaskStatusEnum;
}

