/* tslint:disable */
/* eslint-disable */
/**
 * My FastAPI App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CompletedTask,
  CompletedUser,
  HTTPValidationError,
  Task,
  TaskFailure,
  User,
} from '../models/index';
import {
    CompletedTaskFromJSON,
    CompletedTaskToJSON,
    CompletedUserFromJSON,
    CompletedUserToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    TaskFromJSON,
    TaskToJSON,
    TaskFailureFromJSON,
    TaskFailureToJSON,
    UserFromJSON,
    UserToJSON,
} from '../models/index';

export interface CreateSingleTaskApiV1TasksPostRequest {
    task: Task;
}

export interface CreateSingleUserApiV1UsersPostRequest {
    user: User;
}

export interface DeleteSingleTaskApiV1TasksTaskIdDeleteRequest {
    taskId: number;
}

export interface DeleteSingleUserApiV1UsersUserIdDeleteRequest {
    userId: number;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Create Single Task
     */
    async createSingleTaskApiV1TasksPostRaw(requestParameters: CreateSingleTaskApiV1TasksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CompletedTask>> {
        if (requestParameters['task'] == null) {
            throw new runtime.RequiredError(
                'task',
                'Required parameter "task" was null or undefined when calling createSingleTaskApiV1TasksPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/tasks`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TaskToJSON(requestParameters['task']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CompletedTaskFromJSON(jsonValue));
    }

    /**
     * Create Single Task
     */
    async createSingleTaskApiV1TasksPost(requestParameters: CreateSingleTaskApiV1TasksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CompletedTask> {
        const response = await this.createSingleTaskApiV1TasksPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Single User
     */
    async createSingleUserApiV1UsersPostRaw(requestParameters: CreateSingleUserApiV1UsersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CompletedUser>> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling createSingleUserApiV1UsersPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/users`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserToJSON(requestParameters['user']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CompletedUserFromJSON(jsonValue));
    }

    /**
     * Create Single User
     */
    async createSingleUserApiV1UsersPost(requestParameters: CreateSingleUserApiV1UsersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CompletedUser> {
        const response = await this.createSingleUserApiV1UsersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Single Task
     */
    async deleteSingleTaskApiV1TasksTaskIdDeleteRaw(requestParameters: DeleteSingleTaskApiV1TasksTaskIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling deleteSingleTaskApiV1TasksTaskIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/tasks/{task_id}`;
        urlPath = urlPath.replace(`{${"task_id"}}`, encodeURIComponent(String(requestParameters['taskId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Single Task
     */
    async deleteSingleTaskApiV1TasksTaskIdDelete(requestParameters: DeleteSingleTaskApiV1TasksTaskIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteSingleTaskApiV1TasksTaskIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Delete Single User
     */
    async deleteSingleUserApiV1UsersUserIdDeleteRaw(requestParameters: DeleteSingleUserApiV1UsersUserIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling deleteSingleUserApiV1UsersUserIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/users/{user_id}`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Single User
     */
    async deleteSingleUserApiV1UsersUserIdDelete(requestParameters: DeleteSingleUserApiV1UsersUserIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteSingleUserApiV1UsersUserIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Get Tasks
     */
    async getTasksApiV1TasksGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CompletedTask>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/tasks`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CompletedTaskFromJSON));
    }

    /**
     * Get Tasks
     */
    async getTasksApiV1TasksGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CompletedTask>> {
        const response = await this.getTasksApiV1TasksGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get Tasks
     */
    async getTasksApiV1UsersGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CompletedUser>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/users`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CompletedUserFromJSON));
    }

    /**
     * Get Tasks
     */
    async getTasksApiV1UsersGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CompletedUser>> {
        const response = await this.getTasksApiV1UsersGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Health
     */
    async healthHealthGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/health`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Health
     */
    async healthHealthGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.healthHealthGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Root
     */
    async rootGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Root
     */
    async rootGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.rootGetRaw(initOverrides);
        return await response.value();
    }

}
