/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tasks */
        get: operations["get_tasks_api_v1_tasks_get"];
        put?: never;
        /** Create Single Task */
        post: operations["create_single_task_api_v1_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CompletedTask */
        CompletedTask: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Description */
            description: string;
            status: components["schemas"]["TaskStatusEnum"];
            /** Assignee */
            assignee: string;
            /**
             * Estimated Time
             * Format: duration
             */
            estimated_time: string;
            /**
             * Desired Completion Date
             * Format: date-time
             */
            desired_completion_date: string;
            /** Notes */
            notes?: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * HTTPStatus
         * @description HTTP status codes and reason phrases
         *
         *     Status codes from the following RFCs are all observed:
         *
         *         * RFC 7231: Hypertext Transfer Protocol (HTTP/1.1), obsoletes 2616
         *         * RFC 6585: Additional HTTP Status Codes
         *         * RFC 3229: Delta encoding in HTTP
         *         * RFC 4918: HTTP Extensions for WebDAV, obsoletes 2518
         *         * RFC 5842: Binding Extensions to WebDAV
         *         * RFC 7238: Permanent Redirect
         *         * RFC 2295: Transparent Content Negotiation in HTTP
         *         * RFC 2774: An HTTP Extension Framework
         *         * RFC 7725: An HTTP Status Code to Report Legal Obstacles
         *         * RFC 7540: Hypertext Transfer Protocol Version 2 (HTTP/2)
         *         * RFC 2324: Hyper Text Coffee Pot Control Protocol (HTCPCP/1.0)
         *         * RFC 8297: An HTTP Status Code for Indicating Hints
         *         * RFC 8470: Using Early Data in HTTP
         * @enum {integer}
         */
        HTTPStatus: 100 | 101 | 102 | 103 | 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207 | 208 | 226 | 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308 | 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 421 | 422 | 423 | 424 | 425 | 426 | 428 | 429 | 431 | 451 | 500 | 501 | 502 | 503 | 504 | 505 | 506 | 507 | 508 | 510 | 511;
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Task */
        Task: {
            /** Title */
            title: string;
            /** Description */
            description: string;
            status: components["schemas"]["TaskStatusEnum"];
            /** Estimated Time */
            estimated_time: number;
            /**
             * Desired Completion Date
             * Format: date-time
             */
            desired_completion_date: string;
            /** Notes */
            notes?: string | null;
            /** Assignee */
            assignee?: string | null;
        };
        /** TaskFailure */
        TaskFailure: {
            /** Reason */
            reason: string;
            status: components["schemas"]["HTTPStatus"];
        };
        /**
         * TaskStatusEnum
         * @enum {string}
         */
        TaskStatusEnum: "OPEN" | "IN_PROGRESS" | "BLOCKED" | "COMPLETED";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_tasks_api_v1_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletedTask"][];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskFailure"];
                };
            };
        };
    };
    create_single_task_api_v1_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Task"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletedTask"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskFailure"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskFailure"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
